version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      I3GgfKPoV/8bkSaZxIutNSvkwjrKEyhKQO4TGvUAh7iHC57EEKoz+BDAmZyOfovqQfIwisIGl3FwjtPHxDu7JitGvje+z98kpUYteokc4FfUB2Zm4D82qTBvAjf67hRw/K6hgvTBNIAXujuP7546pLtr+g7W38oV/PJTgviRxLq/c6PjhzYnaJFK6D28AG00LlMG7kO7zcfmljJIXSdpXOsPEsJoiRoJUeSriZH0Fm3VjJzVvrqOONU9Wr6vW/aHwiV+3Sbk64VYnEMUJwM9ay/WoAQ/RpJszW2LGgURe9ZvL6g4r08BLtcw2ps8E8O3IflQObsc08muEiRYXDxicl3S5bvrVFhX6dBcTaaBI2Rq4FB51p1IOsJflPu31jvMtJlk4EMddJGEoT8z8kwAiqsqvoQHa8/m7kVAyNtJ9Lgr5eEoiv6fxFEHkq/aSZwsZa8MC18oeKqR11gtRIiX0dDdKuruzjcPxW6yWQ1JEnWjVyfAwbwkn03tZcWHZj6fGC9fiyBTPUCKCRykk7bASmdvRROQseUfHV3De0VWE7JooztWFOQSWg+EEUdJ54Qiz57xXQLhiaCat0v1xVwiKn6yHeuSi63aY/DviVrvkdwl0cNwo+L7wJMSBmRbJxsdmjIJxptzL1I1L2vDBE2d8elZr92pSv6G+U0aZSHKElA=
